from fastapi import APIRouter, Depends, HTTPException, status
from app.schemas.blacklist import BlacklistRead, BlacklistCreate, BulkBlacklistRequest, BulkBlacklistDeleteRequest
from app.api.deps import get_session, get_current_user
from app.models.blacklist import Blacklist
from app.models.campaign import CampaignRecipient
from app.models.user import User
from sqlmodel import Session, select

router = APIRouter()


@router.post("/bulk")
def bulk_blacklist(
    req: BulkBlacklistRequest,
    session: Session = Depends(get_session),
    current_user: User = Depends(get_current_user),
):
    """Bulk add phone numbers to blacklist. Accepts phone_numbers and/or recipient_ids."""
    if not req.phone_numbers and not req.recipient_ids:
        raise HTTPException(status_code=400, detail="Provide phone_numbers and/or recipient_ids")

    numbers = set(req.phone_numbers)

    # Resolve recipient_ids to phone numbers
    if req.recipient_ids:
        recipients = session.exec(
            select(CampaignRecipient).where(CampaignRecipient.id.in_(req.recipient_ids))
        ).all()
        for r in recipients:
            numbers.add(r.phone_number)

    # Get existing blacklisted numbers for this user
    existing = set(
        session.exec(
            select(Blacklist.phone_number).where(Blacklist.user_id == current_user.id)
        ).all()
    )

    added = 0
    skipped = 0
    for num in numbers:
        if num in existing:
            skipped += 1
            continue
        session.add(Blacklist(phone_number=num, user_id=current_user.id))
        added += 1

    session.commit()
    return {"success": True}


@router.post("/", status_code=status.HTTP_201_CREATED)
def create_blacklist(
    blacklist_in: BlacklistCreate,
    session: Session = Depends(get_session),
    current_user: User = Depends(get_current_user)
):
    """Create a new blacklist entry"""
    # The phone number is already validated and formatted by the schema
    # (see BlacklistCreate.validate_phone format e.g. "1234567890")
    # For DB storage and filtering, we expect the format generated by the schema.
    normalized_phone = blacklist_in.phone_number

    existing_stmt = select(Blacklist).where(
        Blacklist.user_id == current_user.id,
        Blacklist.phone_number == normalized_phone
    )
    existing = session.exec(existing_stmt).first()

    if existing:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Phone number is already blacklisted"
        )

    blacklist_obj = Blacklist(
        phone_number=normalized_phone,
        user_id=current_user.id
    )
    session.add(blacklist_obj)
    session.commit()
    return {"success": True}


@router.get("/", response_model=list[BlacklistRead])
def get_blacklist(
    session: Session = Depends(get_session),
    current_user: User = Depends(get_current_user)
):
    """Get all blacklist entries for the current user"""
    stmt = select(Blacklist).where(Blacklist.user_id == current_user.id)
    results = session.exec(stmt).all()
    return results


@router.delete("/bulk")
def delete_bulk_blacklist(
    req: BulkBlacklistDeleteRequest,
    session: Session = Depends(get_session),
    current_user: User = Depends(get_current_user),
):
    """Delete multiple blacklist entries"""
    if not req.blacklist_ids:
        return {"success": True}

    # Fetch all records to delete
    stmt = select(Blacklist).where(Blacklist.id.in_(req.blacklist_ids), Blacklist.user_id == current_user.id)
    blacklist_objs = session.exec(stmt).all()

    for obj in blacklist_objs:
        session.delete(obj)

    session.commit()
    return {"success": True}

@router.delete("/{blacklist_id}")
def delete_blacklist(
    blacklist_id: int,
    session: Session = Depends(get_session),
    current_user: User = Depends(get_current_user)
):
    """Delete a blacklist entry"""
    stmt = select(Blacklist).where(
        Blacklist.id == blacklist_id,
        Blacklist.user_id == current_user.id
    )
    blacklist_obj = session.exec(stmt).first()

    if not blacklist_obj:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Blacklist entry not found"
        )

    session.delete(blacklist_obj)
    session.commit()
    return {"success": True}